language: python
python:
  - '2.7'
  - '3.3'
  - 'pypy'

install:
  - 'travis_retry pip install -q -e ".[test]" --use-mirrors'
  - 'travis_retry pip install coveralls --use-mirrors'

script: 'py.test --pep8 --cov shield'

after_success: 'coveralls'
